project3Exe: main.o champion.o
   gcc main.o champion.o -o project3Exe
main.o: main.c champion.h
   gcc -c main.c
champion.o: champion.c champion.h
   gcc -c champion.c
clean:
   rm -rf *.o
   rm *.o project3Exe